// src/components/LoanForm.vue
<script setup lang="ts">
import { ref, watch, onMounted } from 'vue'
import { Banknote, CalendarDays, Percent, Printer, MessageSquare, Calendar as CalendarIcon, FileSpreadsheet } from 'lucide-vue-next'
import { LoanSchema, type LoanFormValues } from '@/lib/types'
import { format } from 'date-fns'
import { type DateValue, getLocalTimeZone, today } from '@internationalized/date'
import { cn } from '@/lib/utils'
import Card from './ui/Card.vue'
import CardHeader from './ui/CardHeader.vue'
import CardTitle from './ui/CardTitle.vue'
import CardDescription from './ui/CardDescription.vue'
import CardContent from './ui/CardContent.vue'
import Button from '@/components/ui/button/Button.vue'
import Input from './ui/Input.vue'
import Label from './ui/Label.vue'
import Select from './ui/Select.vue'
import Textarea from './ui/Textarea.vue'
import Slider from './ui/Slider.vue'
import Switch from './ui/Switch.vue'
import Separator from './ui/Separator.vue'
import { Popover, PopoverContent, PopoverTrigger } from '@/components/ui/popover'
import { Calendar } from '@/components/ui/calendar'

const props = defineProps<{
  currency: string
  comments: string
}>()

const emit = defineEmits<{
  calculate: [values: LoanFormValues]
  'update:currency': [value: string]
  'update:comments': [value: string]
  print: []
  'export-excel': []
}>()

const principal = ref(100000)
const interestRate = ref(5)
const loanTerm = ref(30)
const interestType = ref<'compound' | 'simple'>('compound')
const startDate = ref<any>(today(getLocalTimeZone()))

let debounceTimer: ReturnType<typeof setTimeout> | null = null

const calculateSchedule = () => {
  const values = {
    principal: principal.value,
    interestRate: interestRate.value,
    loanTerm: loanTerm.value,
    interestType: interestType.value,
    startDate: startDate.value ? startDate.value.toDate(getLocalTimeZone()) : new Date(),
  }

  const result = LoanSchema.safeParse(values)
  if (result.success) {
    emit('calculate', result.data)
  }
}

const debouncedCalculate = () => {
  if (debounceTimer) clearTimeout(debounceTimer)
  debounceTimer = setTimeout(calculateSchedule, 500)
}

watch([principal, interestRate, loanTerm, interestType, startDate], debouncedCalculate)

onMounted(() => {
  calculateSchedule()
})
</script>

<template>
  <Card>
    <CardHeader>
      <CardTitle>Loan Details</CardTitle>
      <CardDescription>Enter your loan information to see the schedule.</CardDescription>
    </CardHeader>

    <CardContent class="space-y-6">
      <!-- Loan Principal -->
      <div class="space-y-2">
        <Label>Loan Principal ({{ currency }})</Label>
        <div class="relative">
          <Banknote class="absolute left-2.5 top-2.5 h-4 w-4 text-muted-foreground" />
          <Input
            v-model.number="principal"
            type="number"
            step="1000"
            placeholder="e.g., 250000"
            class="pl-8"
          />
        </div>
      </div>

      <!-- Interest Rate -->
      <div class="space-y-2">
        <Label>Annual Interest Rate (%)</Label>
        <div class="relative">
          <Percent class="absolute left-2.5 top-2.5 h-4 w-4 text-muted-foreground" />
          <Input
            v-model.number="interestRate"
            type="number"
            step="0.01"
            placeholder="e.g., 6.5"
            class="pl-8"
          />
        </div>
      </div>

      <!-- Loan Term -->
      <div class="space-y-4">
        <Label class="flex items-center gap-2">
          <CalendarDays class="h-4 w-4 text-muted-foreground" />
          Loan Term (Years): {{ loanTerm }}
        </Label>
        <Slider
          :model-value="[loanTerm]"
          @update:model-value="(v) => { if (v?.[0]) loanTerm = v[0] }"
          :min="1"
          :max="40"
          :step="1"
        />
      </div>

      <!-- Start Date -->
      <div class="space-y-2">
        <Label>Loan Start Date</Label>
        <Popover>
          <PopoverTrigger as-child>
            <Button
              variant="outline"
              :class="cn(
                'w-full justify-start text-left font-normal flex items-center',
                !startDate && 'text-muted-foreground',
              )"
            >
              <CalendarIcon class="mr-2 h-4 w-4 opacity-50" />
              <span class="whitespace-nowrap">{{ startDate ? format(startDate.toDate(getLocalTimeZone()), "PPP") : "Pick a date" }}</span>
            </Button>
          </PopoverTrigger>
          <PopoverContent class="w-auto p-0">
            <Calendar v-model="startDate" initial-focus />
          </PopoverContent>
        </Popover>
      </div>

      <!-- Interest Type -->
      <div class="space-y-2">
        <Label>Interest Type</Label>
        <div class="flex items-center gap-3">
          <span :class="['text-sm transition-colors', interestType === 'simple' ? 'text-foreground font-medium' : 'text-muted-foreground']">Simple</span>
          <Switch
            :checked="interestType === 'compound'"
            @update:checked="(checked) => interestType = checked ? 'compound' : 'simple'"
          />
          <span :class="['text-sm transition-colors', interestType === 'compound' ? 'text-foreground font-medium' : 'text-muted-foreground']">Compound</span>
        </div>
      </div>

      <Separator />

      <!-- Currency -->
      <div class="space-y-2">
        <Label>Report Settings</Label>
        <Select :model-value="currency" @update:model-value="emit('update:currency', $event)">
          <option value="USD">USD ($)</option>
          <option value="EUR">EUR (€)</option>
          <option value="GBP">GBP (£)</option>
          <option value="JPY">JPY (¥)</option>
          <option value="INR">INR (₹)</option>
        </Select>
      </div>

      <!-- Comments -->
      <div class="space-y-2">
        <Label>Personal Comments</Label>
        <div class="relative">
          <MessageSquare class="absolute left-2.5 top-2.5 h-4 w-4 text-muted-foreground z-10" />
          <Textarea
            :model-value="comments"
            @update:model-value="emit('update:comments', $event)"
            placeholder="Add notes for your report..."
            class="pl-8"
          />
        </div>
      </div>

      <!-- Action Buttons -->
      <div class="grid grid-cols-2 gap-4">
        <Button @click="emit('print')" class="w-full">
          Print PDF
          <template #icon>
            <Printer class="h-4 w-4" />
          </template>
        </Button>
        <Button @click="emit('export-excel')" class="w-full" variant="outline">
          Export Excel
          <template #icon>
            <FileSpreadsheet class="h-4 w-4" />
          </template>
        </Button>
      </div>
    </CardContent>
  </Card>
</template>

// src/components/loan-form.tsx
'use client'

import { useEffect } from 'react'
import { useForm } from 'react-hook-form'
import { zodResolver } from '@hookform/resolvers/zod'
import { Banknote, CalendarDays, Percent, Printer, MessageSquare, Calendar as CalendarIcon } from 'lucide-react'
import { format } from 'date-fns'

import { LoanSchema, type LoanFormValues, type AmortizationResult } from '@/lib/types'
import { cn } from '@/lib/utils'

import { Button } from '@/components/ui/button'
import { Calendar } from '@/components/ui/calendar'
import { Popover, PopoverContent, PopoverTrigger } from '@/components/ui/popover'
import { Card, CardContent, CardDescription, CardHeader, CardTitle, CardFooter } from '@/components/ui/card'
import { Form, FormControl, FormField, FormItem, FormLabel, FormMessage } from '@/components/ui/form'
import { Input } from '@/components/ui/input'
import { RadioGroup, RadioGroupItem } from '@/components/ui/radio-group'
import { Slider } from '@/components/ui/slider'
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select'
import { Separator } from './ui/separator'
import { Textarea } from './ui/textarea'


interface LoanFormProps {
  onCalculate: (data: AmortizationResult | null, error?: string) => void;
  currency: string;
  onCurrencyChange: (currency: string) => void;
  generateAmortizationSchedule: (values: LoanFormValues) => { data?: AmortizationResult; error?: string };
  comments: string;
  onCommentsChange: (comments: string) => void;
  onPrint: () => void;
}

export function LoanForm({ onCalculate, currency, onCurrencyChange, generateAmortizationSchedule, comments, onCommentsChange, onPrint }: LoanFormProps) {
  const form = useForm<LoanFormValues>({
    resolver: zodResolver(LoanSchema),
    defaultValues: {
      principal: 100000,
      interestRate: 5,
      loanTerm: 30,
      interestType: 'compound',
      startDate: new Date(),
    },
    mode: 'onChange'
  })

  useEffect(() => {
    const subscription = form.watch((watchedValues) => {
      const result = generateAmortizationSchedule(watchedValues as LoanFormValues);
      if (result.error) {
        onCalculate(null, result.error);
      } else {
        onCalculate(result.data ?? null);
      }
    });
    return () => subscription.unsubscribe();
  }, [form.watch, onCalculate, generateAmortizationSchedule]);

  // Trigger initial calculation
  useEffect(() => {
    const result = generateAmortizationSchedule(form.getValues());
    if (result.data) {
      onCalculate(result.data);
    }
  }, []);

  return (
    <Card>
      <CardHeader>
        <CardTitle>Loan Details</CardTitle>
        <CardDescription>Enter your loan information to see the schedule.</CardDescription>
      </CardHeader>
      <Form {...form}>
        <form onSubmit={(e) => e.preventDefault()}>
          <CardContent className="grid gap-6">
            <FormField
              control={form.control}
              name="principal"
              render={({ field }) => (
                <FormItem>
                  <FormLabel>Loan Principal ({currency})</FormLabel>
                  <div className="relative">
                    <Banknote className="absolute left-2.5 top-2.5 h-4 w-4 text-muted-foreground" />
                    <FormControl>
                      <Input type="number" step="1000" placeholder="e.g., 250000" className="pl-8" {...field} onChange={e => field.onChange(parseFloat(e.target.value))} />
                    </FormControl>
                  </div>
                  <FormMessage />
                </FormItem>
              )}
            />
            <FormField
              control={form.control}
              name="interestRate"
              render={({ field }) => (
                <FormItem>
                  <FormLabel>Annual Interest Rate (%)</FormLabel>
                  <div className="relative">
                    <Percent className="absolute left-2.5 top-2.5 h-4 w-4 text-muted-foreground" />
                    <FormControl>
                      <Input type="number" step="0.01" placeholder="e.g., 6.5" className="pl-8" {...field} onChange={e => field.onChange(parseFloat(e.target.value))} />
                    </FormControl>
                  </div>
                  <FormMessage />
                </FormItem>
              )}
            />
            <FormField
              control={form.control}
              name="loanTerm"
              render={({ field }) => (
                <FormItem>
                  <FormLabel>Loan Term (Years): {field.value}</FormLabel>
                   <div className="relative flex items-center">
                    <CalendarDays className="absolute left-2.5 top-1/2 -translate-y-1/2 h-4 w-4 text-muted-foreground" />
                    <FormControl>
                      <Slider
                        min={1}
                        max={40}
                        step={1}
                        value={[field.value]}
                        onValueChange={(value) => field.onChange(value[0])}
                        className="py-2 pl-8"
                      />
                    </FormControl>
                  </div>
                  <FormMessage />
                </FormItem>
              )}
            />
             <FormField
              control={form.control}
              name="startDate"
              render={({ field }) => (
                <FormItem className="flex flex-col">
                  <FormLabel>Loan Start Date</FormLabel>
                  <Popover>
                    <PopoverTrigger asChild>
                      <FormControl>
                        <Button
                          variant={"outline"}
                          className={cn(
                            "pl-3 text-left font-normal",
                            !field.value && "text-muted-foreground"
                          )}
                        >
                          {field.value ? (
                            format(field.value, "PPP")
                          ) : (
                            <span>Pick a date</span>
                          )}
                          <CalendarIcon className="ml-auto h-4 w-4 opacity-50" />
                        </Button>
                      </FormControl>
                    </PopoverTrigger>
                    <PopoverContent className="w-auto p-0" align="start">
                      <Calendar
                        mode="single"
                        selected={field.value}
                        onSelect={field.onChange}
                        initialFocus
                      />
                    </PopoverContent>
                  </Popover>
                  <FormMessage />
                </FormItem>
              )}
            />
            <FormField
              control={form.control}
              name="interestType"
              render={({ field }) => (
                <FormItem className="space-y-3">
                  <FormLabel>Interest Type</FormLabel>
                  <FormControl>
                    <RadioGroup
                      onValueChange={field.onChange}
                      defaultValue={field.value}
                      className="flex space-x-4"
                    >
                      <FormItem className="flex items-center space-x-2 space-y-0">
                        <FormControl>
                          <RadioGroupItem value="compound" />
                        </FormControl>
                        <FormLabel className="font-normal">Compound</FormLabel>
                      </FormItem>
                      <FormItem className="flex items-center space-x-2 space-y-0">
                        <FormControl>
                          <RadioGroupItem value="simple" />
                        </FormControl>
                        <FormLabel className="font-normal">Simple</FormLabel>
                      </FormItem>
                    </RadioGroup>
                  </FormControl>
                  <FormMessage />
                </FormItem>
              )}
            />
            <Separator />
            <div className="space-y-2">
              <FormLabel>Report Settings</FormLabel>
              <Select value={currency} onValueChange={onCurrencyChange}>
                  <SelectTrigger>
                      <SelectValue placeholder="Select Currency" />
                  </SelectTrigger>
                  <SelectContent>
                      <SelectItem value="USD">USD ($)</SelectItem>
                      <SelectItem value="EUR">EUR (€)</SelectItem>
                      <SelectItem value="GBP">GBP (£)</SelectItem>
                      <SelectItem value="JPY">JPY (¥)</SelectItem>
                      <SelectItem value="INR">INR (₹)</SelectItem>
                  </SelectContent>
              </Select>
            </div>
            <FormItem>
              <FormLabel>Personal Comments</FormLabel>
              <div className="relative">
                <MessageSquare className="absolute left-2.5 top-2.5 h-4 w-4 text-muted-foreground" />
                <FormControl>
                  <Textarea
                    placeholder="Add notes for your report..."
                    className="pl-8"
                    value={comments}
                    onChange={(e) => onCommentsChange(e.target.value)}
                  />
                </FormControl>
              </div>
            </FormItem>
          </CardContent>
          <CardFooter>
            <Button onClick={onPrint} className="w-full" variant="outline">
              <Printer className="mr-2 h-4 w-4" />
              Print / Save as PDF
            </Button>
          </CardFooter>
        </form>
      </Form>
    </Card>
  )
}
